
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["RECIPE_APP_DATABASE_USERNAME"] %>
  password: <%= ENV["RECIPE_APP_DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: Recipe_App_development

test:
  <<: *default
  database: Recipe_App_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
